final commodityImages = {
  "Alsandikai": "https://drive.google.com/uc?export=view&id=1Tvdjwhu6Ca-A1-cciAvcQ4pnXI50hdTw",
  "Amaranthus": "https://drive.google.com/uc?export=view&id=1xrniYaczUk_OZeSDRfW7SAdrHYZUIyKr",
  "Amla(Nelli Kai)": "https://drive.google.com/uc?export=view&id=1OwhHVo15p4D1CqL5vWQ24sIraGLkMeJW",
  "Apple": "https://drive.google.com/uc?export=view&id=1adn8GK953UO0XQDAUmegrBcYc-6bcaSJ",
  "Arecanut(Betelnut/Supari)": "https://drive.google.com/uc?export=view&id=11F1oCcomshYMseWkCVeSkikWshs0JSX8",
  "Arhar Dal(Tur Dal)": "https://drive.google.com/uc?export=view&id=1UgHMz5ARMA2tbxXngnyjVrue3MqsHoGV",
  "Arhar(Tur/Red Gram)(Whole)": "https://drive.google.com/uc?export=view&id=1UgHMz5ARMA2tbxXngnyjVrue3MqsHoGV",
  "Ashgourd": "https://drive.google.com/uc?export=view&id=1d9rqpUBcN_AozRoQu4Ca3LyRjLKyHhad",
  "Banana": "https://drive.google.com/uc?export=view&id=1NN6phikmRwKexueDEi1t-zgUqISpE7qV",
  "Banana - Green": "https://drive.google.com/uc?export=view&id=14CWIUG7Tn_QojX9VRDspL7MrAgOI9D4W",
  "Barley(jau)": "https://drive.google.com/uc?export=view&id=1C2e5_ftF_IcG4fLk4sWxbdZwDmhjASPX",
  "Beetroot": "https://drive.google.com/uc?export=view&id=1fVBeJN7cygzOscI3_74OrPeUl2jtWlKK",
  "Bengal Gram Dal (Chana Dal)": "https://drive.google.com/uc?export=view&id=1KPGKiYlaLVN-DpvUmlAPWMyniC5chpBd",
  "Bengal Gram(Gram)(whole)": "https://drive.google.com/uc?export=view&id=1UgHMz5ARMA2tbxXngnyjVrue3MqsHoGV",
  "Bengal Gram(Gram)(Whole)": "https://drive.google.com/uc?export=view&id=1UgHMz5ARMA2tbxXngnyjVrue3MqsHoGV",
  "Bhindi(Ladies Finger)": "https://drive.google.com/uc?export=view&id=1WYqtZ2doODtb3XnMroDZTphRAyBVuc8K",
  "Bitter gourd": "https://drive.google.com/uc?export=view&id=111PFGLj3jCKykQcOyJvPjmdlUz8iQ0Di",
  "Black Gram (Urd Beans)(Whole)": "https://drive.google.com/uc?export=view&id=1meLC6Hq8NAeVskgqf01e6fIKNwlT9_0b",
  "Black Gram Dal (Urd Dal)": "https://drive.google.com/uc?export=view&id=1meLC6Hq8NAeVskgqf01e6fIKNwlT9_0b",
  "Black pepper": "https://drive.google.com/uc?export=view&id=1R0Os4JEKnaZ-yPHqNRAg0VoaKU8decwC",
  "Bottle gourd": "https://drive.google.com/uc?export=view&id=1x-F8chyRmSY5cIwINjmTgiJQ-NZl_Yqj",
  "Brinjal": "https://drive.google.com/uc?export=view&id=1kmyiQERPy0Vs4hdctNX7hyJzAz-Pq82-",
  "Cabbage": "https://drive.google.com/uc?export=view&id=1vzfGspKlqgT16DLZlXYhbbVNYDxlyCwo",
  "Capsicum": "https://drive.google.com/uc?export=view&id=164KNmSQ7NHosFOdL1Ifp9qD8t_pJ8Mz",
  "Carrot": "https://drive.google.com/uc?export=view&id=1L7dsuSqZwSNvZgflPd5oGp3vK4Dp6DhE",
  "Cauliflower": "https://drive.google.com/uc?export=view&id=1XhjZbtQByDB8BB0Fz4L3jK7MSZ2nC8tC",
  "Chikoos(Sapota)": "https://drive.google.com/uc?export=view&id=1S4pMhIJdo3KpI3UP7l2om_24crJkoFft",
  "Cluster beans": "https://drive.google.com/uc?export=view&id=1yPjAz_ZBmpp0YOPVcu8MFL_u7Mwf_Lcl",
  "Coconut": "https://drive.google.com/uc?export=view&id=1QQtuXnF5NJXCGaIEzlDXj0NGyBkR0tJo",
  "Coconut Oil": "https://drive.google.com/uc?export=view&id=1gQu3op-4-srodcvqmgtWdGiSyysy0XMs",
  "Coconut Seed": "https://drive.google.com/uc?export=view&id=1rQSaeH8-TxakM1-nutz9MXpkKEgJwUk8",
  "Coffee": "https://drive.google.com/uc?export=view&id=1F0ofxnK7zcDaj1q3CKYL0-93ac9ODpsb",
  "Colacasia": "https://drive.google.com/uc?export=view&id=",
  "Cowpea(Labia/Karamani)": "https://drive.google.com/uc?export=view&id=1SS9m-dLjD_U3zzEogTCZqy-iYhdTHLyL",
  "Cucumber(Kheera)": "https://drive.google.com/uc?export=view&id=1m-jDMh6I_EsvtLGHtQS-Cr4EjHhrRJST",
  "Cucumbar(Kheera)": "https://drive.google.com/uc?export=view&id=1m-jDMh6I_EsvtLGHtQS-Cr4EjHhrRJST",
  "Cummin Seed(Jeera)": "https://drive.google.com/uc?export=view&id=1sHU_UShQarR8vHOqacSMoJg2HhlqzSaS",
  "Elephant Yam(Suran)": "https://drive.google.com/uc?export=view&id=1NcWqCLZPYRUC99VsKLtjaMVMgx0bzyI9",
  "Field Pea": "https://drive.google.com/uc?export=view&id=1mb9DAQWg5xtq5K-yrFgDoT8A9QTNBcc4",
  "Foxtail Millet(Nannave)": "https://drive.google.com/uc?export=view&id=",
  "French Beans(Frasbean)": "https://drive.google.com/uc?export=view&id=1sANh0WG56-1nJ1kKWWwC8egXUIHHjpJU",
  "Garlic": "https://drive.google.com/uc?export=view&id=14kg2cXER7WYJBsyDzxrPoG4FdEZ9xcRt",
  "Ginger(Dry)": "https://drive.google.com/uc?export=view&id=19YuGiuwi2qDEOEgyo-2rCoCOeZBr8L9L",
  "Ginger(Green)": "https://drive.google.com/uc?export=view&id=19YuGiuwi2qDEOEgyo-2rCoCOeZBr8L9L",
  "Grapes": "https://drive.google.com/uc?export=view&id=1hUYEVB11JnIu4p0jg6hABaREqMOrbarY",
  "Green Avare(W)": "https://drive.google.com/uc?export=view&id=1_vbb1gcjtuw2maoFDRG9onsqU8pb8lgs",
  "Green Chilli": "https://drive.google.com/uc?export=view&id=1yuEr71vm-h7LOPwgmuntKDh3k5khRv8k",
  "Green Gram Dal (Moong Dal)": "https://drive.google.com/uc?export=view&id=1UgHMz5ARMA2tbxXngnyjVrue3MqsHoGV",
  "Green Gram Dal(Moong Dal)": "https://drive.google.com/uc?export=view&id=1sou98Vjtj7JM08tCql-VhHapetCQO8H5",
  "Green Gram(Moong)(Whole)": "https://drive.google.com/uc?export=view&id=16t7wavshVM9PLSB7pfTHp8SUvkyDtFMn",
  "Green Peas": "https://drive.google.com/uc?export=view&id=1mFws0lm2Rk_xiPgDD_jR_hGr8a19dVkU",
  "Ground Nut Seed": "https://drive.google.com/uc?export=view&id=1_TCqjD53E6Hr_VZd2_ixS73PPAUT5r0D",
  "Groundnut": "https://drive.google.com/uc?export=view&id=1qIxtiOphetCd3ICWOQh2Cd-7FBzJrj2j",
  "Guar": "https://drive.google.com/uc?export=view&id=1a2yOHfjvFA3LNjQcWCwqLWwc8J96LYUz",
  "Guar Seed(Cluster Beans Seed)": "https://drive.google.com/uc?export=view&id=14PrCc9D2FsxC3QZDvBHSM03gf2d7Mcao",
  "Guava": "https://drive.google.com/uc?export=view&id=1z0o5w-JDMvfrwx2aYAp874lGPGZABxpF",
  "Gur(Jaggery)": "https://drive.google.com/uc?export=view&id=1J4pf__4_9H1m7OKVSco5La0ppyHC1s4R",
  "Indian Beans(Seam)": "https://drive.google.com/uc?export=view&id=1nVRkj10nR2uzyYbWz0_xrysyWRnd8JQr",
  "Isabgul(Psyllium)": "https://drive.google.com/uc?export=view&id=13r_cTW8vmHGxlZUR7DfHoS3hhtXA8GaX",
  "Jack Fruit": "https://drive.google.com/uc?export=view&id=1jCWtA3I2pPkjY-Y_BygJe6hVtS9FikN3",
  "Jute": "https://drive.google.com/uc?export=view&id=",
  "Kabuli Chana(Chickpeas-White)": "https://drive.google.com/uc?export=view&id=1w83IuGxR70CXA-MVlsX4Hf9SGa6EzptW",
  "Karbuja(Musk Melon)": "https://drive.google.com/uc?export=view&id=1TDxQl7UJU1EMFzld57ktop4o1CVpfizx",
  "Kulthi(Horse Gram)": "https://drive.google.com/uc?export=view&id=15OTIDvjuVui6pysGnvWwUspypbQG13nY",
  "Leafy Vegetable": "https://drive.google.com/uc?export=view&id=1v-Y-iJowW6mG_qH-xfCQYVyuKeLz9JBS",
  "Lemon": "https://drive.google.com/uc?export=view&id=14bG8BB9cqNMg_-NbHdg3wbD3N2qSP80m",
  "Lentil(Mansur)(Whole)": "https://drive.google.com/uc?export=view&id=1kiPIk8owyDPAwJm1g6bdXw5F1loUNVyd",
  "Lime": "https://drive.google.com/uc?export=view&id=12HL26onVYHCuqBVue02rPoS7xN_Y4hfq",
  "Little gourd(Kundru)": "https://drive.google.com/uc?export=view&id=",
  "Long Melon(Kakri)": "https://drive.google.com/uc?export=view&id=15cDUlemDW9A0LBJgoSJrAw3TacPFrzcF",
  "Mango":"https://drive.google.com/uc?export=view&id=1QlsMSfnsov2P13ddBFX3gHnD_hJkzl0_",
  "Mashrooms": "https://drive.google.com/uc?export=view&id=1eDLdEaffnwGuCNSx_QC7rmWSyMoloADR",
  "Masur Dal": "https://drive.google.com/uc?export=view&id=1EJCKKgUYKBdmJmwP4ep-Q2eQMrkg7AJm",
  "Mataki": "https://drive.google.com/uc?export=view&id=",
  "Methi Seeds": "https://drive.google.com/uc?export=view&id=",
  "Methi(Leaves)": "https://drive.google.com/uc?export=view&id=",
  "Mint(Pudina)": "https://drive.google.com/uc?export=view&id=1nsvGS0-9gYrxGPq36Yg60gB0qvNil16e",
  "Mousambi(Sweet Lime)": "https://drive.google.com/uc?export=view&id=1Ln9YSq0Wckiujrt5OwgLLQNZa3Ie5ItK",
  "Muskmelon": "https://drive.google.com/uc?export=view&id=1jFkQXZ1z1vw-HxsppcMnZhmf3TfyjCw8",
  "Mustard": "https://drive.google.com/uc?export=view&id=1MSUSf_DJ36FUYak6tIsCcTL8RMXPogNM",
  "Mustard Oil": "https://drive.google.com/uc?export=view&id=1vISMJemGhZR0jiBbrA3edl37ojVdtwD0",
  "Onion": "https://drive.google.com/uc?export=view&id=1yxTYKYlpaLYsMx4xRhd5u6jTazPBZDxU",
  "Onion Green": "https://drive.google.com/uc?export=view&id=1yxTYKYlpaLYsMx4xRhd5u6jTazPBZDxU",
  "Orange": "https://drive.google.com/uc?export=view&id=1U_tV_QuHPwge2UxHCoLPzBmI4MOeE7Y5",
  "Paddy(Dhan)(Common)": "https://drive.google.com/uc?export=view&id=1bSxdoqQHS1GP9_BQkVr84amq1bggpUNk",
  "Papaya": "https://drive.google.com/uc?export=view&id=1O21OHVLZlgqACzI_ru-gAfXYrA3_tK9x",
  "Papaya(Raw)": "https://drive.google.com/uc?export=view&id=1O21OHVLZlgqACzI_ru-gAfXYrA3_tK9x",
  "Peas Wet": "https://drive.google.com/uc?export=view&id=1mFws0lm2Rk_xiPgDD_jR_hGr8a19dVkU",
  "Pepper garbled": "https://drive.google.com/uc?export=view&id=16ajlmp4Szt7WH0yRqRTPeIiU0-ABigkn",
  "Pepper ungarbled": "https://drive.google.com/uc?export=view&id=18Ua8yhCrcq3LWOjhu3xTP8DNQoOYJGtH",
  "Pineapple": "https://drive.google.com/uc?export=view&id=1Ypd8YByeKBTFRvkh8PqItaq_8pgtVBQc",
  "Pointed gourd(Parval)": "https://drive.google.com/uc?export=view&id=1x-F8chyRmSY5cIwINjmTgiJQ-NZl_Yqj",
  "Pomegranate": "https://drive.google.com/uc?export=view&id=1Ojhm8a2cvkbUJoyHxc7-i6_dGYwZgJgs",
  "Potato": "https://drive.google.com/uc?export=view&id=1zRG8dKuSbuZDOFLQh7ZsHS3GTS_KIPVK",
  "Pumpkin": "https://drive.google.com/uc?export=view&id=1EwxoxAhVTgGHh9yEoNNRuko-8zPpcqhK",
  "Raddish": "https://drive.google.com/uc?export=view&id=1CBCNMT_nYi7evjta2K0kn4FZE-ezA0ks",
  "Ridgegaurd(Tori)": "https://drive.google.com/uc?export=view&id=111PFGLj3jCKykQcOyJvPjmdlUz8iQ0Di",
  "Snakegourd": "https://drive.google.com/uc?export=view&id=15cDUlemDW9A0LBJgoSJrAw3TacPFrzcF",
  "Spinach":"https://drive.google.com/uc?export=view&id=1v-Y-iJowW6mG_qH-xfCQYVyuKeLz9JBS",
  "Sponge gourd": "https://drive.google.com/uc?export=view&id=1Ncx0GE4Aeo-iVH9o5fSNIAb6EUcUiy8s",
  "Squash(Chappal Kadoo)": "https://drive.google.com/uc?export=view&id=1EwxoxAhVTgGHh9yEoNNRuko-8zPpcqhK",
  "Sunflower": "https://drive.google.com/uc?export=view&id=14hIw-YEeUYmNvEjFll2p15ne1TO0kQxC",
  "Sunflower Seed": "https://drive.google.com/uc?export=view&id=14hIw-YEeUYmNvEjFll2p15ne1TO0kQxC",
  "Suran(Elephant Foot Yam)": "https://drive.google.com/uc?export=view&id=1NcWqCLZPYRUC99VsKLtjaMVMgx0bzyI9",
  "Sweet potato": "https://drive.google.com/uc?export=view&id=1o5R-4cJ46QdAwdw3cIaMJEmOAM-jn3uC",
  "Tamarind": "https://drive.google.com/uc?export=view&id=1h6lt2bHg6Gw4RKOrNm1mvLcQa-OkMMHw",
  "Tamarind Seed": "https://drive.google.com/uc?export=view&id=1h6lt2bHg6Gw4RKOrNm1mvLcQa-OkMMHw",
  "Tamarind Seed (Hull)": "https://drive.google.com/uc?export=view&id=1h6lt2bHg6Gw4RKOrNm1mvLcQa-OkMMHw",
  "Tapioca": "https://drive.google.com/uc?export=view&id=1hYgWxXe4tD6Qs7TJbEgvn3M1oY0WMlXq",
  "Tinda(Indian Round Gourd)": "https://drive.google.com/uc?export=view&id=1o9RGxVHTxl6nB7t_8oN4rPc01vIUMVIf",
  "Tomato": "https://drive.google.com/uc?export=view&id=1vYTUWGCaSLR0MjmK4jqXJMrjMfQzMvR8",
  "Turmeric (raw)": "https://drive.google.com/uc?export=view&id=19YuGiuwi2qDEOEgyo-2rCoCOeZBr8L9L",
  "Walnut kernel": "https://drive.google.com/uc?export=view&id=1MnzS6zQlQWJzf5gyqqpF_3TGXyymLHqR",
  "Walnut Shell": "https://drive.google.com/uc?export=view&id=1MnzS6zQlQWJzf5gyqqpF_3TGXyymLHqR",
  "Wheat": "https://drive.google.com/uc?export=view&id=1aZby-pLV-mLrAEoC5vN7GOl-m6xV0ULw",
  "Wheat Atta": "https://drive.google.com/uc?export=view&id=1Lg9JNRvP6Z1r02s_1b_dTIInJr7l39gB",
  "Wheat Flour": "https://drive.google.com/uc?export=view&id=1Lg9JNRvP6Z1r02s_1b_dTIInJr7l39gB",
  "White Peas": "https://drive.google.com/uc?export=view&id=1UQcqBCk0XU2BZ-xCf_j9-DTmkI2z3bEN",
  "Wood-Sarkanda": "https://drive.google.com/uc?export=view&id=1Fv3R-VmbgTfWJbC8mqwT22vBd2CzI7Gq",
  "Yam": "https://drive.google.com/uc?export=view&id=1NcWqCLZPYRUC99VsKLtjaMVMgx0bzyI9",
  "Yam (Ratalu)": "https://drive.google.com/uc?export=view&id=1NcWqCLZPYRUC99VsKLtjaMVMgx0bzyI9",
  "Yellow Peas": "https://drive.google.com/uc?export=view&id=1UQcqBCk0XU2BZ-xCf_j9-DTmkI2z3bEN",
  "Water Melon":"https://drive.google.com/uc?export=view&id=1ggB1kRzCMc3YKXubknszwZiP8ba6eJdw"
};
