# pubspec.yaml

name: cropsync
description: "A new Flutter project."
publish_to: 'none' 
version: 1.2.0+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core & Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.3
  firebase_messaging: ^14.8.2
  firebase_database: ^10.5.7
  firebase_storage: ^11.7.7
  google_sign_in: ^6.2.1

  # State Management (Recommendation: Choose one)
  provider: ^6.1.2
  get: ^4.6.6
  flutter_bloc: ^8.1.5

  # UI & UX
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  weather_icons: ^3.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  curved_navigation_bar: ^1.0.3
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  card_swiper: ^3.0.1
  font_awesome_flutter: ^10.7.0
  salomon_bottom_bar: ^3.3.2
  
  # Utilities
  gsheets: ^0.5.0
  http: ^1.2.1
  url_launcher: ^6.2.6
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  intl: ^0.20.2 # Version for localization
  shared_preferences: ^2.2.3
  pull_to_refresh: ^2.0.0
  image_picker: ^1.1.2
  webview_flutter: ^4.8.0
  google_generative_ai: ^0.4.4
  flutter_markdown: ^0.7.3+1
  mime: ^1.0.5
  mailto: ^2.0.0
  flutter_local_notifications: ^17.2.2
  video_player: ^2.9.1
  flutter_dotenv: ^5.1.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  rename: ^3.0.2

# Configuration for App Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/S.png"
  min_sdk_android: 21 
  
# Flutter-specific configuration
flutter:
  generate: true # Enables code generation for localization
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - .env