class GramsData {
    static String soilType = "Loamy Soil";
    static String seedRate = "6 to 8 kg/acre";
    static String seedTreatment = "Fungicides: Control fungal diseases in seeds. Examples: metalaxyl, carbendazim.\nInsecticides: Protect seeds from insect pests. Examples: imidacloprid, thiamethoxam.\nInoculants: Contain helpful microorganisms for soil health. Example: rhizobia bacteria for legumes.\nBiostimulants: Boost seed germination and plant growth. Includes plant hormones and nutrients.\nCoatings: Improve seed flow and emergence. Contains polymers and nutrients.";

    static String growingSeason = "October - November";
    static String cropDuration = "100-120 days";

    static String irrigationSchedule = "Pre-sowing: Ensure soil moisture is adequate for germination. Pre-irrigation may be necessary if soil moisture is low.\nGermination to Seedling Establishment (1-3 weeks): Irrigate every 7-10 days to support seedling establishment. Apply moderate irrigation to maintain soil moisture.\nVegetative Growth (4-8 weeks): Increase irrigation frequency to every 10-12 days, depending on soil moisture and rainfall. Provide sufficient water for vigorous vegetative growth.\nCritical Growth Stages (Vegetative Growth, Flowering): Maintain consistent soil moisture during these stages. Irrigate every 10-15 days or as needed.\nLate Growth Stage (Pod Development to Maturity): Gradually reduce irrigation frequency as the crop matures. Avoid overwatering during pod development to prevent fungal diseases.";

    static String nutrientRequirement = "Nitrogen (N): 40-60 kg\nPhosphorus (P): 20-30 kg\nPotassium (K): 20-30 kg";

    static String weedManagement = "Cultural Practices: Crop rotation, proper seedbed preparation, and optimal planting density help suppress weeds in chickpea fields.\nMechanical Control: Hand weeding, inter-row cultivation, and shallow tillage can effectively manage weeds in chickpea crops.\nChemical Control:\nPre-emergence herbicides: Pendimethalin, Metribuzin, and Trifluralin are commonly used pre-emergence herbicides for weed control in chickpeas.\nPost-emergence herbicides: Post-emergence herbicides like Imazethapyr, Bentazon, and Metsulfuron-methyl are used to control emerged weeds in chickpea fields.";

    static String diseaseAndPestManagement = "Diseases:\nWhite Rust / Downy Mildew\nSymptoms: White pustules, stem swelling. Use treated seeds and copper sprays.\nManagement: Treat seeds, use sprays, opt for healthy seeds, control weeds, and rotate crops.\nAlternaria Leaf Spot\nSymptoms: Brown spots, defoliation. Use healthy seeds and copper sprays.\nManagement: Use healthy seeds, sprays, and rotate crops.\nGrain Mold\nSymptoms: Discolored grains, reduced yield. Avoiding prolonged moisture, timely harvesting, and fungicide sprays can mitigate the disease.\nManagement: Timely harvesting, use of fungicides (e.g., Benlate, Propiconazole), and ensuring proper ventilation during storage.\nErgot\nSymptoms: Blackened grains, honeydew exudation. Mechanical cleaning of seeds and fungicide sprays (e.g., Benlate, Propiconazole) can help control ergot.\nManagement: Clean seeds mechanically, use fungicide sprays, and maintain proper sanitation practices in the field.\nPests:\nMustard Aphid\nSymptoms: Leaf curling, stunted growth. Use yellow traps and soap or neem oil sprays.\nManagement: Choose tolerant varieties, use traps, apply neem oil, and consider Dimethoate sprays.\nPainted Bug\nSymptoms: Wilting, withering. Early sowing, irrigation, quick threshing, and Dimethoate sprays help.\nManagement: Plow deeply, sow early, irrigate, thresh quickly, and use Dimethoate.\nMustard Sawfly\nSymptoms: Shot holes, drying leaves. Summer plowing, early sowing, and bitter gourd seed oil sprays are effective.\nManagement: Plow in summer, sow early, irrigate, cultivate cleanly, and use Quinalphos sprays.\nGram Pod Borer\nSymptoms: Larvae bore into pods, causing damage to seeds. Handpicking affected pods and applying neem oil can help control them.\nManagement: Monitor fields regularly, handpick affected pods, and use neem oil sprays.\nWhitefly\nSymptoms: Whiteflies feed on leaves, causing yellowing and wilting. Yellow sticky traps and neem oil sprays are effective management methods.\nManagement: Use yellow sticky traps, apply neem oil sprays, and maintain good field hygiene.";

    static String intercultivation = "Weed Control: Regular weeding is essential to prevent competition for nutrients and sunlight. Manual weeding or shallow cultivation can be employed to control weeds.\nIntercropping: Intercropping with compatible crops like maize, sorghum, or pigeon pea can help in maximizing land utilization and enhancing soil fertility.\nMulching: Applying mulch helps in conserving soil moisture, suppressing weed growth, and maintaining soil temperature, thus promoting better growth of black and green grams.\nCrop Rotation: Rotating black and green grams with non-leguminous crops helps in breaking disease cycles and improving soil health by reducing pest and disease pressure.\nFertilization: Proper fertilization with balanced nutrients is crucial for optimal growth. Application of organic manures like compost or farmyard manure can supplement soil fertility.";

    static String harvesting = "February - March";

    static String postHarvesting = "Harvesting: Pick beans when they're dry but still in the pod to prevent shattering.\nDrying: Dry harvested beans until they reach less than 13% moisture content to avoid spoilage.\nThreshing: Separate beans from pods either manually or using a thresher.\nCleaning: Remove any debris or damaged beans from the harvest to ensure quality.\nGrading: Sort beans based on size and quality to meet market standards and preferences.\nStorage: Store cleaned beans in dry, well-ventilated containers to maintain freshness and prevent mold growth.\nPackaging: Pack beans in sealed bags or containers with proper labeling for identification.\nTransportation: Handle beans with care during transportation to prevent damage and maintain quality.";
}
