
class JowarData {
    static String soilType = "Sandy Loam Soil, Loamy Soil";
    static String seedRate = "3.6-4 kg/acre";
    static String seedTreatment = "Treat the seed with Thiomethaxam @ 3 g/kg seed and Thiram or Captan @ 3 g/kg seed.";

    static String growingSeason = "(K) June - July  (R) November - December";
    static String cropDuration = "100-120 days";

    static String irrigationSchedule = "Pre-sowing: Ensure soil moisture is adequate for germination. Pre-irrigation may be required if soil moisture is low.\nGermination to Seedling Establishment (1-3 weeks): Irrigate every 7-10 days to support seedling establishment. Apply moderate irrigation to maintain soil moisture.\nVegetative Growth (4-8 weeks): Increase irrigation frequency to every 10-12 days, depending on soil moisture. Provide sufficient water for vigorous vegetative growth.\nCritical Growth Stages (Tillering, Flowering): Maintain consistent soil moisture during these stages. Irrigate every 10-15 days or as needed.\nLate Growth Stage (Maturity): Gradually reduce irrigation frequency as the crop matures. Avoid overwatering to prevent lodging.";

    static String nutrientRequirement = "Nitrogen (N): 40-60 kg\nPhosphorus (P): 20-30 kg\nPotassium (K): 20-30 kg";

    static String weedManagement = "Cultural Practices: Adequate soil fertility management, proper row spacing, and timely weed removal help manage weeds in jowar cultivation.\nMechanical Control: Hand weeding, inter-row cultivation, and rotary hoeing are effective mechanical methods for weed control in jowar fields.\nChemical Control:\nPre-emergence herbicides: Atrazine, Metribuzin, and Pendimethalin are commonly used pre-emergence herbicides for weed control in jowar.\nPost-emergence herbicides: Post-emergence herbicides like 2,4-D, Metsulfuron-methyl, and Glyphosate are used to control emerged weeds in jowar crops.";

    static String diseaseAndPestManagement = "Shootfly:\nSymptoms: Maggot feeds on growing tip causing wilting and drying of central leaf (dead heart).\nCultural Control: Adjust planting time to avoid vulnerable crop stages. Increase seed rate and remove dead heart seedlings.\nChemical Control: Seed treatment with Furadan or imidacloprid. Spray with methyl demeton or neem seed kernel extract.\nStem Borer:\nSymptoms: Larvae feed on whorl leaves, causing transparent windows. Stem tunnelling leads to dead heart.\nCultural Control: Uproot and burn stubbles, chop stems.\nChemical Control: Apply Malathion or Furadan into whorls. Use Carbofuran granules or Metasystox spray.\nShootbug:\nSymptoms: Leaves dry and twist, plant death may occur.\nChemical Control: Spray with phosphomidon or Dimethoate.\nAphids:\nSymptoms: Yellowing leaves, honeydew production.\nChemical Control: Spray with Metasystox or Dimethoate. Treat seeds with imidacloprid or thiamethoxam.\nEar Head Midge:\nSymptoms: Red maggots in grains, grain drying.\nManagement: Spray cypermethrin at flowering and milk stages.\nMites:\nSymptoms: Webbing on leaves, leaf redness and drying.\nManagement: Spray Dimethoate or Dicofol.\nGrainmold Damage:\nSymptoms: Discolored grains, yield loss.\nCultural Control: Avoiding rain-prone maturity periods, timely harvesting and drying.\nChemical Control: Spray with Aureofungin or Captan.\nErgot:\nSymptoms: Honeydew exudation, blackened grains.\nControl: Wash seeds in salt solution, spray with benlate or Propiconazole.\nPlant Rot:\nSymptoms: Black or pink fungus growth on grains.\nManagement: Spray Mancozeb during flowering, soft dough, and ripening stages.\nLeaf Spot:\nSymptoms: Leaf diseases due to rain and humidity.\nManagement: Spray Zaineb or Mancozeb as needed.";

    static String intercultivation = "Weeding: Remove weeds around jowar plants by hand or with tools.\nMulching: Cover soil around jowar with organic materials to reduce weeds and retain moisture.\nInter-row Cultivation: Loosen soil between rows to improve aeration and water absorption.\nThinning: Remove excess jowar plants to give others more space to grow.\nIntercropping: Plant compatible crops between jowar rows to maximize land use.\nCompanion Planting: Grow beneficial plants alongside jowar to improve soil and deter pests.\nCrop Rotation: Alternate jowar with different crops each season to maintain soil health.";

    static String harvesting = "(K) September - October  (R) March - April";

    static String postHarvesting = "Harvesting: Harvest jowar when grains are fully mature and hard. Cut the stalks near the base using a sickle or a mechanical harvester.\nDrying: Spread harvested jowar in a thin layer to dry under the sun. Ensure grains are thoroughly dried to prevent mold growth.\nThreshing: Separate grains from the stalks by beating or treading on the harvested jowar. Use mechanical threshers for larger quantities.\nWinnowing: Use wind or a fan to separate grains from chaff and other debris. Perform winnowing outdoors on a breezy day.\nCleaning: Remove remaining debris and foreign matter from the grains. Use sieves or screens to clean the grains thoroughly.\nStorage: Store cleaned and dried jowar grains in airtight containers or bags. Keep in a cool, dry place to prevent moisture absorption and insect infestation.\nPackaging: Package jowar grains in clean and labeled bags or containers. Include information such as harvest date and variety.\nQuality Control: Regularly inspect stored jowar for signs of spoilage or pests. Take corrective measures if any issues are detected to maintain grain quality.";
}
