class MustardData {
    static String soilType = "Sandy Loam Soil";
    static String seedRate = "1.6 to 2 kg/acre";
    static String seedTreatment = "Treat the seeds according to the disease incidence in your region. In areas where stem rot is more prevalent, the seeds should be treated with Carbendazim @ 2g/1kg seed.\n" 
            "Seed treatment with imidacloprid 70 WS @ 5g/kg of seed provides good control to painted bugs up to 30-35 DAS.";

    static String growingSeason = "October - November";
    static String cropDuration = "100-120 days";

    static String irrigationSchedule = "Pre-sowing: Ensure soil moisture is adequate for germination. Pre-irrigation may be required if soil moisture is low.\nGermination to Seedling Establishment (1-3 weeks): Irrigate every 7-10 days to support seedling establishment. Apply moderate irrigation to maintain soil moisture.\nVegetative Growth (4-8 weeks): Increase irrigation frequency to every 10-12 days, depending on soil moisture and rainfall. Provide sufficient water for vigorous vegetative growth.\nCritical Growth Stages (Vegetative Growth, Flowering): Maintain consistent soil moisture during these stages. Irrigate every 10-15 days or as needed.\nLate Growth Stage (Pod Development to Maturity): Gradually reduce irrigation frequency as the crop matures. Avoid overwatering during pod development to prevent fungal diseases.";

    static String nutrientRequirement = "Nitrogen (N): 20-30 kg\nPhosphorus (P): 30-40 kg\nPotassium (K): 20-30 kg";

    static String weedManagement = "Cultural Practices: Proper seedbed preparation, crop rotation, and timely weeding help manage weeds in mustard fields.\nMechanical Control: Hand weeding, inter-row cultivation, and shallow tillage can effectively manage weeds in mustard crops.\nChemical Control:\nPre-emergence herbicides: Pendimethalin, Metribuzin, and Fluchloralin are commonly used pre-emergence herbicides for weed control in mustard.\nPost-emergence herbicides: Post-emergence herbicides like 2,4-D, Metsulfuron-methyl, and Quizalofop-P-ethyl are used to control emerged weeds in mustard fields.";

    static String diseaseAndPestManagement= "Pests:\nMustard Aphid\nSymptoms: Sap-sucking leads to leaf curling, stunted growth, and sooty mold. Yellow sticky traps can monitor populations. Soft soap or neem oil sprays are effective.\nManagement: Use tolerant varieties, employ traps, apply neem oil or soap sprays, and consider chemical control like Dimethoate.\nPainted Bug\nSymptoms: Sap-sucking causes wilting and withering. Early sowing and irrigation can reduce damage. Quick threshing and crop burning help prevent spread.\nManagement: Deep plowing, early sowing, irrigation, quick threshing, and Dimethoate sprays are recommended.\nMustard Sawfly\nSymptoms: Larvae feed on leaves, causing shot holes and drying. Summer plowing, early sowing, clean cultivation, and bitter gourd seed oil sprays are effective.\nManagement: Summer plowing, early sowing, irrigation, clean cultivation, and Quinalphos sprays are recommended.\nDiseases:\nWhite Rust / Downy Mildew\nSymptoms: White pustules on leaves, stem swelling, and distortion. Seed treatment and foliar sprays with Bordeaux mixture or copper oxychloride help manage the disease.\nManagement: Seed treatment, foliar sprays, use of disease-free seeds, weed control, and crop rotation.\nAlternaria Leaf Spot\nSymptoms: Circular brown spots on leaves, stem lesions, and defoliation. Use of healthy seeds and foliar sprays with copper oxychloride aid in disease control.\nManagement: Use healthy seeds, foliar sprays, and crop rotation for disease management.";

    static String intercultivation = "Weeding: Remove weeds manually or with tools to prevent competition for nutrients and water.\nMulching: Apply organic mulch around mustard plants to suppress weed growth and conserve soil moisture.\nInter-row Cultivation: Loosen soil between mustard rows to improve root development and water infiltration.\nThinning: Thin out crowded mustard plants to provide adequate space for growth and airflow.\nIntercropping: Plant compatible crops between mustard rows to maximize land productivity and diversity.\nCompanion Planting: Grow companion plants alongside mustard to repel pests and enhance soil health.\nCrop Rotation: Rotate mustard with different crops in successive seasons to prevent disease buildup and improve soil fertility.";

    static String harvesting = "February - March";

    static String postHarvesting = "Harvest Timing: Harvest the crop when the pods turn yellowish-brown to ensure optimum maturity.\nAvoid delayed harvesting to prevent shattering and minimize losses.\nPrecautions Against Shattering: Harvest just before the pods open to prevent seed loss due to shattering.\nStacking Before Threshing: Stack the harvested crop on the threshing floor for 5-6 days to allow for drying and curing.\nThreshing Process: Thresh the dried crop to separate grain from husk.\nUtilize slow-moving natural air currents to aid in the separation process.\nHusking Separation: Ensure efficient separation of threshed grain from husk for further processing and storage.";
}
