class SoyabeanData {
    static String soilType = "Loamy Soil";
    static String seedRate = "16-20 kg/acre";
    static String seedTreatment = "Fungicides: Use fungicides such as metalaxyl, carbendazim, or thiram to control fungal diseases like seed rot and damping-off.\nInsecticides: Apply insecticides like imidacloprid or thiamethoxam to protect against seed and soil-borne pests such as aphids and bean leaf beetles.\nInoculants: Use rhizobium inoculants to promote nitrogen fixation by forming nodules on soybean roots, improving plant health and yield potential.";

    static String growingSeason = "October - November";
    static String cropDuration = "90-120 days";

    static String irrigationSchedule = "Pre-sowing: Ensure soil moisture is adequate for germination. Pre-irrigation may be necessary if soil moisture is low.\nGermination to Seedling Establishment (1-3 weeks): Irrigate every 7-10 days to support seedling establishment. Apply moderate irrigation to maintain soil moisture.\nVegetative Growth (4-8 weeks): Increase irrigation frequency to every 10-12 days, depending on soil moisture and rainfall. Provide sufficient water for vigorous vegetative growth.\nCritical Growth Stages (Vegetative Growth, Flowering, Pod Development): Maintain consistent soil moisture during these stages. Irrigate every 7-10 days or as needed.\nLate Growth Stage (Pod Development to Maturity): Gradually reduce irrigation frequency as the crop matures. Avoid overwatering during pod development to prevent fungal diseases.";

    static String nutrientRequirement = "Nitrogen (N): 60-80 kg\nPhosphorus (P): 40-50 kg\nPotassium (K): 30-40 kg";

    static String weedManagement = "Cultural Practices: Adequate soil fertility management, proper row spacing, and timely weed removal help manage weeds in soybean cultivation.\nMechanical Control: Hand weeding, inter-row cultivation, and rotary hoeing are effective mechanical methods for weed control in soybean fields.\nChemical Control:\nPre-emergence herbicides: Pendimethalin, Metribuzin, and Imazethapyr are commonly used pre-emergence herbicides for weed control in soybean.\nPost-emergence herbicides: Post-emergence herbicides like Glyphosate, Imazethapyr, and Quizalofop-P-ethyl are used to control emerged weeds in soybean crops.";

    static String diseaseAndPestManagement = "Diseases:\nWhite Rust / Downy Mildew:\nSymptoms: White pustules on leaves, stem swelling.\nControl: Seed treatment with garlic extract, foliar sprays of Bordeaux mixture, disease-free seeds.\nAlternaria Leaf Spot:\nSymptoms: Circular brown spots on leaves, stem lesions.\nControl: Healthy seeds, copper oxychloride sprays, weed management, crop rotation.\nGrain Mold Damage:\nSymptoms: Discolored grains, reduced yield.\nControl: Avoiding rainy maturation periods, timely harvesting, fungicide sprays, seed treatment.\nErgot:\nSymptoms: Blackened grains, honeydew exudation.\nControl: Mechanical seed cleaning, fungicide sprays (Benlate, Propiconazole), sanitation.\nPests:\nAphids:\nSymptoms: Leaf curling, stunted growth, sooty mold.\nManagement: Use tolerant varieties, sticky traps, neem oil or soap sprays, Dimethoate.\nPainted Bug:\nSymptoms: Wilting, withering due to sap-sucking.\nManagement: Deep plowing, early sowing, irrigation, quick threshing, Dimethoate sprays.\nSawfly:\nSymptoms: Leaves with shot holes, drying.\nManagement: Summer plowing, early sowing, clean cultivation, bitter gourd seed oil, Quinalphos sprays.";

    static String intercultivation = "Weeding: Remove weeds manually or with tools to prevent competition for nutrients and space.\nMulching: Cover the soil around soybean plants with organic materials to suppress weeds and conserve moisture.\nInter-row Cultivation: Loosen the soil between rows to enhance root development, improve water infiltration, and reduce weed growth.\nThinning: Remove excess soybean plants to provide adequate spacing for optimal growth and yield.\nIntercropping: Plant compatible crops between soybean rows to maximize land use and diversify farm output.\nCompanion Planting: Grow companion plants alongside soybeans to enhance soil fertility, attract beneficial insects, and repel pests.\nCrop Rotation: Rotate soybeans with different crops in subsequent seasons to break pest and disease cycles and maintain soil health.";

    static String harvesting = "September - October";

    static String postHarvesting = "Harvesting: Pick soybeans when they're dry but not yet shedding from the pod.\nDrying: Dry harvested beans until they're less than 13% moisture to prevent spoilage.\nThreshing: Separate beans from pods using a thresher or by hand.\nCleaning: Remove any debris or damaged beans from the harvest.\nGrading: Sort beans by size and quality to meet market standards.\nStorage: Store cleaned beans in dry, well-ventilated containers to keep them fresh.\nPackaging: Put beans in sealed bags or containers with proper labeling.\nTransportation: Handle beans carefully during transport to prevent damage.";
}
