// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkD1eBCVqKJSG3DK0xjXsD9LOXnS1EkZM',
    appId: '1:460953027509:web:a99c35cd1a88ad7705cffc',
    messagingSenderId: '460953027509',
    projectId: 'cropsync-244a3',
    authDomain: 'cropsync-244a3.firebaseapp.com',
    storageBucket: 'cropsync-244a3.appspot.com',
    measurementId: 'G-CERYXG5454',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-2PNFk5n8ayBiHdtuoVWkDGlOVY6bzqg',
    appId: '1:460953027509:android:3499a2b07696e15305cffc',
    messagingSenderId: '460953027509',
    projectId: 'cropsync-244a3',
    storageBucket: 'cropsync-244a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5crlFkkuCcszQga-40Qimar_4xXmuCAE',
    appId: '1:460953027509:ios:25381a687d0ceec705cffc',
    messagingSenderId: '460953027509',
    projectId: 'cropsync-244a3',
    storageBucket: 'cropsync-244a3.appspot.com',
    iosBundleId: 'com.example.panache14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5crlFkkuCcszQga-40Qimar_4xXmuCAE',
    appId: '1:460953027509:ios:25381a687d0ceec705cffc',
    messagingSenderId: '460953027509',
    projectId: 'cropsync-244a3',
    storageBucket: 'cropsync-244a3.appspot.com',
    iosBundleId: 'com.example.panache14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkD1eBCVqKJSG3DK0xjXsD9LOXnS1EkZM',
    appId: '1:460953027509:web:a23430f7e9fc8c4305cffc',
    messagingSenderId: '460953027509',
    projectId: 'cropsync-244a3',
    authDomain: 'cropsync-244a3.firebaseapp.com',
    storageBucket: 'cropsync-244a3.appspot.com',
    measurementId: 'G-ZYY9TCQ7BB',
  );

}