// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDluitXWo4L6r37Ek4cEFWe8PW-aNXAKyE',
    appId: '1:938319022397:web:f021ce20f6596d873b1d54',
    messagingSenderId: '938319022397',
    projectId: 'cropsync-ed120',
    authDomain: 'cropsync-ed120.firebaseapp.com',
    storageBucket: 'cropsync-ed120.appspot.com',
    measurementId: 'G-JHD9EP97D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtLozR3uRV194CFVmNSVGezA3MvbGrZQ',
    appId: '1:938319022397:android:9099b8e0c9c1ff933b1d54',
    messagingSenderId: '938319022397',
    projectId: 'cropsync-ed120',
    storageBucket: 'cropsync-ed120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpK0rntriyux1YoEjMBWlu7YIQEP2FiU',
    appId: '1:938319022397:ios:c642aeb0d88a63463b1d54',
    messagingSenderId: '938319022397',
    projectId: 'cropsync-ed120',
    storageBucket: 'cropsync-ed120.appspot.com',
    iosBundleId: 'com.example.panache14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpK0rntriyux1YoEjMBWlu7YIQEP2FiU',
    appId: '1:938319022397:ios:c642aeb0d88a63463b1d54',
    messagingSenderId: '938319022397',
    projectId: 'cropsync-ed120',
    storageBucket: 'cropsync-ed120.appspot.com',
    iosBundleId: 'com.example.panache14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDluitXWo4L6r37Ek4cEFWe8PW-aNXAKyE',
    appId: '1:938319022397:web:4a9055afac7a33be3b1d54',
    messagingSenderId: '938319022397',
    projectId: 'cropsync-ed120',
    authDomain: 'cropsync-ed120.firebaseapp.com',
    storageBucket: 'cropsync-ed120.appspot.com',
    measurementId: 'G-FD2E9P28G6',
  );
}
